name: Linux OS(Ubuntu) 0.15.0-dev nightly compilation-

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linux_nightly:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - uses: mlugg/setup-zig@v2
      with:
        version: master
    - name: make
      run: |
        sudo apt install libopengl-dev libgl1-mesa-dev
        sudo apt install libglfw3 libglfw3-dev
        sudo apt install libsdl2-dev libsdl2-ttf-dev
        make
